apiVersion: v1
kind: Deployment
metadata:
  name: eks-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-apache
  template:
    metadata:
      labels:
        app: eks-apache
    spec:
      containers:
      - name: apache
        image: AWS_ECR_URI
        ports:
        - containerPort: 80
        imagePullPolicy: Always